In [ ]:
#1 Write a Python program to compute the eigenvalues and eigenvectors of a given square array.
from numpy import array
from numpy.linalg import eig

A = array([
[1, 0, 2, 3],
[1, 3, 0, 2],
[2, 0, 1, 3],
[0, 3, 2, 1]])
print(A)

# factorize
values, vectors = eig(A)
print ('the Eigen Values are:') 
print(values)
print('the Eigen Vector are:')
print (vectors)


[[1 0 2 3]
 [1 3 0 2]
 [2 0 1 3]
 [0 3 2 1]]
the Eigen Values are:
[ 6.         -1.30277564 -1.          2.30277564]
the Eigen Vector are:
[[-0.5         0.48531808 -0.60606061  0.61508353]
 [-0.5         0.21075352 -0.18181818 -0.47213312]
 [-0.5         0.48531808 -0.39393939  0.61508353]
 [-0.5        -0.6960716   0.66666667 -0.14295041]]


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
# Q2
# Define determinant of a 2 by 2 matrix
def det2x2(m):
  return m[0][0] * m[1][1] - m[0][1] * m[1][0]

# Define your martix
matrix = [
    [ 1, 2, 3],
    [ 5, 2, 9],
    [ 2, 3, 1]
]

a, b, c = matrix[0]

print("matrix:")
for array in matrix: print(array)
print()

# Define determinant of a 3 by 3 matrix

efhi = [x[1:] for  x in matrix[1:]]

dfgi = [x[::2] for x in matrix[1:]]

degh = [x[0:2] for x in matrix[1:]]        

det = (
    a * det2x2(efhi)
    -b * det2x2(dfgi)
    +c * det2x2(degh)
)
# Print Determinant

print(f'Determinant = {det}')


matrix:
[1, 2, 3]
[5, 2, 9]
[2, 3, 1]

Determinant = 34


In [ ]:
#3 Write a Python program that solves a system of inequalities with a 4 x 4 square matrix A where Ax=b.
import numpy as np
from numpy import array

A = np.matrix([
[1, 2, 3,5],
[4, 5, 6,7],
[7, 8, 9,8],
[3,7,6,4]])

b = np.matrix([
[-1, 1, 4,6],
[2, 3, -2,4],
[7, 8, 9,8],
[3,7,6,4]])
np.linalg.solve(A,b)

matrix([[  0.2       ,  -2.2       , -15.8       ,  -6.8       ],
        [ -2.4       ,  -3.6       , -29.4       , -12.4       ],
        [  4.53333333,   8.46666667,  54.53333333,  22.53333333],
        [ -2.        ,  -3.        , -17.        ,  -6.        ]])

In [6]:
from google.colab import drive
drive.mount ('/content/drive')
!pwd

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content


In [8]:
%%shell
jupyter nbconvert --to html //content/drive/MyDrive/Python_HW_2.ipynb

[NbConvertApp] Converting notebook //content/drive/MyDrive/Python_HW_2.ipynb to html
[NbConvertApp] Writing 287416 bytes to //content/drive/MyDrive/Python_HW_2.html
